library/booklibrary/urls.py
from django.conf.urls import url
from . import views

app_name = 'booklibrary'


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'login/$',views.login,name='login'),
    url(r'register/$',views.register,name='register'),
    url(r'loginhandler/$',views.loginhandler,name='loginhandler'),
    url(r'registerhandler/$',views.registerhandler,name='registerhandler'),
    url(r'checkstuinfo/(.*?)/$',views.checkstuinfo,name='checkstuinfo'),
    url(r'updatestuinfo/(.*?)/$',views.updatestuinfo,name='updatestuinfo'),
    url(r'checkbook/(.*?)/$',views.checkbook,name='checkbook'),
    url(r'bookdetail/(.*?)/(.*?)/$',views.bookdetail,name='bookdetail'),
    # url(r'borrow/(.*?)/(.*?)/$',views.borrow,name='borrow'),
    url(r'show_borrows/$',views.show_borrows,name='show_borrows'),
    url(r'upload/$',views.upload,name='upload'),
    url(r'edit/$',views.edit,name='edit'),
    url(r'email/$',views.email,name='email'),
    url(r'active/(.*?)/$',views.active,name='active'),
    url(r'^ajax/$',views.ajax,name='ajax'),
    url(r'^ajaxajax/$',views.ajaxajax,name='ajaxajax'),
    url(r'^verify/$',views.verify,name='verify'),
    url(r'^echarts/$',views.echarts,name='echarts'),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('booklibrary.urls',namespace='booklibrary')),
]

from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

library/booklibrary/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta,datetime
from tinymce.models import HTMLField
# import datetime
# Create your models here.
class StudentUser(User):
     college = models.CharField(max_length=20,null=True,blank=True)
     sno = models.IntegerField(null=True,blank=True)
     def __str__(self):
          return self.username



class Book(models.Model):
     bookname = models.CharField(max_length=20)
     author = models.CharField(max_length=20)
     publish_com = models.CharField(max_length=20)
     publish_date = models.DateField()
     def __str__(self):
          return self.bookname

class History(models.Model):
     book = models.ForeignKey(Book,on_delete=models.CASCADE)
     user = models.ForeignKey(User,on_delete=models.CASCADE)
     date_borrow = models.DateTimeField(default=datetime.now())
     date_return = models.DateTimeField(default=datetime.now()+timedelta(days=30))
     status = models.BooleanField()


class Hotpic(models.Model):
    name = models.CharField(max_length=20)
    index = models.SmallIntegerField(unique=True)
    pic = models.ImageField(upload_to='hotpic')

    def __str__(self):
        return self.name

class Message(models.Model):
    title = models.CharField(max_length=30)
    message = HTMLField()

    def __str__(self):
        return self.title

library/booklibrary/views.py
from django.shortcuts import render,redirect,reverse
from django.http import request,HttpResponse,HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail,send_mass_mail
from .models import *
from PIL import Image,ImageDraw,ImageFont
import random,io
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,SignatureExpired
# Create your views here.

def index(request):
    hotpics = Hotpic.objects.all().order_by('index')
    messages = Message.objects.all()
    return render(request,'booklibrary/index.html',{'hotpics':hotpics,'messages':messages})


def login(request):
    return render(request,'booklibrary/reader_login.html')


def loginhandler(request):
    username = request.POST['username']
    pwd = request.POST['password']
    verifycode = request.POST["verifycode"]

    try:
        stu = StudentUser.objects.get(username=username)
        # print(stu.password,pwd)
        if stu.is_active:
            if stu.password == pwd:
                if verifycode == request.session["verifycode"]:
                    return render(request, 'booklibrary/reader.html', {'stu': stu})
                else:
                    return HttpResponse("验证码错误")
                # return render(request,'booklibrary/reader.html',{'stu':stu})
                # return HttpResponse('success')
            else:
                return render(request, 'booklibrary/reader_login.html', {'error': '密码错误'})
        else:
            return render(request, 'booklibrary/reader_login.html', {'error': '账户未激活'})
    except:
        # return HttpResponse('error')
        return render(request, 'booklibrary/reader_login.html', {'error': '用户名或密码错误'})


def verify(request):
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20,100),
    random.randrange(20,100),
    random.randrange(20,100))
    width = 100
    heigth = 25
    # 创建画面对象
    im = Image.new('RGB',(width,heigth),bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, heigth))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    font = ImageFont.truetype('pala.ttf', 23)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    request.session['verifycode'] = rand_str
    f = io.BytesIO()
    im.save(f,'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(f.getvalue(), 'image/png')


def register(request):
    return render(request,'booklibrary/register.html')

def registerhandler(request):
    username = request.POST['username']
    pwd = request.POST['password']
    cpwd = request.POST['password2']
    college = request.POST['college']
    sno = request.POST['number']
    email = request.POST['email']
    print(username,pwd,cpwd,college,sno,email)

    try:
        if pwd == cpwd:
            user = StudentUser()
            user.username = username
            user.password = pwd
            user.college = college
            user.sno = sno
            user.email = email
            user.is_active = False


            user.save()
            id = StudentUser.objects.get(username = username).id
            serutil = Serializer(settings.SECRET_KEY,300)
            idstr = serutil.dumps({'userid':id}).decode('utf-8')
            send_mail('激活账户', '<a href = "http://127.0.0.1:8000/booklibrary/active/%s">点击激活</a>' % (idstr,),settings.DEFAULT_FROM_EMAIL,[email])
            return redirect(reverse('booklibrary:login'))
    except:
        return HttpResponse('error')


def checkstuinfo(request,id):
    user = StudentUser.objects.get(pk = id)

    return render(request,'booklibrary/reader_info.html',{'user':user})

def updatestuinfo(request,id):
    if request.method == 'GET':
        user = StudentUser.objects.get(pk = id)
        print(user)
        return render(request,'booklibrary/reader_modify.html',{'user':user})
    if request.method == 'POST':
        username = request.POST['username']
        pwd = request.POST['password']
        college = request.POST['college']
        sno = request.POST['number']
        email = request.POST['email']
        user = StudentUser.objects.get(pk = id)
        user.username = username
        user.college = college
        user.sno = sno
        user.email = email

        if pwd == '':
            pwd = user.password
            user.password = pwd
            print(username,pwd,college,sno,email)
            user.save()
        else:
            user.password = pwd
            user.save()

        return redirect(reverse('booklibrary:checkstuinfo',args=(user.id,)))

def checkbook(request,id):
    stu = StudentUser.objects.get(pk = id)
    # print(stu)
    # return HttpResponse('success')
    if request.method == 'GET':
        return render(request,'booklibrary/reader_query.html',{'stu':stu})

    if request.method == "POST":
        option = request.POST['item']
        check = request.POST['query']
        try:
            if option == 'name':
                books = Book.objects.all().filter(bookname = check)
                print(books)
                # return HttpResponse('success')
                return render(request, 'booklibrary/reader_query.html', {'stu': stu, 'books': books})
            elif option == 'author':
                books = Book.objects.all().filter(author = check)
                print(books)
                return render(request, 'booklibrary/reader_query.html', {'stu': stu, 'books': books})
        except:
            return HttpResponse('error')

def bookdetail(request,bookid,stuid):
    stu = StudentUser.objects.get(pk = stuid)
    book = Book.objects.get(pk = bookid)
    try:
        reader = History.objects.all().filter(book =book).filter(status = True)[0]
        if reader.status == False:
            reader = None
    except:
        reader = None
    if request.method == "GET":


        return render(request,'booklibrary/reader_book.html',{"book":book,'reader':reader,'stu':stu})
    elif request.method == 'POST':
        if reader is None:
            error = None
            saveborrowinfo(bookid,stuid)

            print(type(reader))
            return HttpResponseRedirect('/booklibrary/bookdetail/' + str(book.id) + '/' + str(stu.id) + '/',{"error": error})

            # return reader(request,'booklibrary/reader_book.html',{"book":book,'reader':reader,'stu':stu})
        else:
            if reader.status:
                print("aaaaaaaaaaa")
                error = '借阅过'
            else:
                saveborrowinfo(bookid, stuid)
            return render(request, 'booklibrary/reader_book.html', {"book": book, 'reader': reader, 'stu': stu, "error":error})


def saveborrowinfo(bookid,stuid):
    stu = StudentUser.objects.get(pk=stuid)
    book = Book.objects.get(pk=bookid)
    borrow = History()
    borrow.user = stu
    borrow.book = book
    borrow.status = True
    borrow.save()


def show_borrows(request):
    borrows = History.objects.all()
    return render(request,'booklibrary/reader_histroy.html',{'histroys':borrows})


def upload(request):
    if request.method == 'GET':
        return render(request,'booklibrary/reader_upload.html')
    if request.method == 'POST':
        name = request.POST['name']
        index = request.POST['index']
        pic = request.FILES['pic']

        hot = Hotpic(name= name,index= index,pic = pic)
        hot.save()
        return redirect(reverse('booklibrary:index'))


def edit(request):
    if request.method == 'GET':
        return render(request,'booklibrary/edit.html')
    elif request.method == 'POST':
        title = request.POST['title']
        message = request.POST['message']
        msg = Message(title = title, message = message)
        msg.save()
        return redirect(reverse('booklibrary:index'))


def email(request):
    try:
        send_mail('Django send email','django send email',settings.DEFAULT_FROM_EMAIL,['1195741928@qq.com'])
    except:
        return HttpResponse('send error')

    return HttpResponse('send success')

def active(request,idstr):
    try:
        dser = Serializer(settings.SECRET_KEY,300)
        obj = dser.loads(idstr)
        user = StudentUser.objects.get(id=obj['userid'])
        user.is_active = True
        user.save()
        return redirect(reverse('booklibrary:login'))
    except SignatureExpired as e:
        return HttpResponse('error')


def ajax(request):
    return render(request,'booklibrary/ajax.html')

def ajaxajax(request):
    return HttpResponse('success')


def echarts(request):
    return render(request,'booklibrary/echarts.html')

library/templates/booklibrary/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $('#load').click(function(){
                $.ajax({
                    url:'/ajaxajax/',
                    type:'post',
                    data:{'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val()},
                    success:function (data) {
                        console.log(data)
                    }
                })
            })
        })
    </script>
</head>
<body>
    {% csrf_token %}
    <button id="load">点击</button>

</body>
</html>

library/templates/booklibrary/echarts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>显示图表</title>
    <script src="https://www.echartsjs.com/examples/vendors/echarts/echarts.min.js"></script>

</head>
<body>
    <div id="info1" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('info1'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
</body>
</html>

library/templates/booklibrary/edit.html
{% extends 'booklibrary/layout.html' %}

{% block link %}
<script src="/static/tiny_mce/tiny_mce.js"></script>
<script>
    tinyMCE.init({
    'mode':'textareas',
    'theme':'advanced',
    'width':680,
    'height':300
    });
</script>
{% endblock %}
{% block body %}
    <h2>文本编辑</h2>
    <form action="{% url 'booklibrary:edit' %}" method="post">
        {% csrf_token %}
        标题：<input type="text" name="title">
        <br>
        内容: <textarea name="message" id="" cols="30" rows="10">

            </textarea>
        <br>
        <input type="submit" value="发布">
    </form>
{% endblock %}

library/templates/booklibrary/index.html
{% extends "booklibrary/layout.html" %}
{% block title %}主页{% endblock %}
{% block link %}

  <a href="{% url 'booklibrary:login' %}">读者登录 </a>
{% endblock %}

{% block body %}
  <h2>欢迎使用</h2>
<!--<div class="hotpic">-->
  <!--{% for pic in hotpics %}-->
  <!--<img src="/static/media/{{pic.pic.url}}" alt="无法加载">-->
  <!--{% empty %}-->
  <!--{% endfor %}-->
<!--</div>-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

   <ol class="carousel-indicators">
     {% for i in hotpics %}
     {% if i.index == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
     {% else %}
     <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
     {% endif %}
     {% endfor %}

  </ol>

  <div class="carousel-inner">

    {% for pic in hotpics %}
    {% if pic.index == 1 %}
    <div class="carousel-item active">
      <img class="d-block w-100" src="/static/media/{{pic.pic.url}}" alt="">
    </div>
    {% else %}

    <div class="carousel-item ">
      <img class="d-block w-100" src="/static/media/{{pic.pic.url}}" alt="First slide">
    </div>
    {% endif %}

    {% endfor %}


  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div>
    {% for message in messages %}
        {{message.message|safe}}
    {% endfor %}
</div>
{% endblock %}

library/templates/booklibrary/layout.html
<!doctype html>
<title> {% block title %} 图书管理系统 {% endblock %} </title>
        {% block linkcss %}{% endblock %}
<link rel=stylesheet type=text/css href="/static/css/style.css">

<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" ></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" >
<div class=page>
  <h1>图书管理系统</h1>
  <div class=navigation>
    {% block link %}{% endblock %}
  </div>
  <div class=body>
    {% block body %}{% endblock %}
   </div>
  <div class=footer>
     &mdash; by-qikuedu
  </div>
</div>
    

library/templates/booklibrary/reader.html
{% extends 'booklibrary/layout.html' %}
{% block title %} 欢迎使用 {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:index' %}"> 注销[{{stu.username}}] </a> |
	<a href="{% url 'booklibrary:checkbook' stu.id %}"> 查询 </a> |
	<a href="{% url 'booklibrary:checkstuinfo' stu.id %}"> 查看个人信息 </a> |
	<a href="{% url 'booklibrary:show_borrows' %}"> 查看阅读记录 </a>

{% endblock %}

{% block body %}
	<h2> 欢迎使用 </h2>
{% endblock %}

library/templates/booklibrary/reader_book.html
{% extends 'booklibrary/layout.html' %}

{% block title %} 书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href=""> 返回 </a>
	{% endif %}
{% endblock %}

{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}
	<h2> 书目信息 </h2>
	{% if book %}
	<li> ISBN            	{{book.id}} </li>
	<li> 书名        		{{book.bookname}} </li>
	<li> 作者        		{{book.author}} </li>	
	<li> 出版社     	{{book.publish_com}} </li>
	<li> 出版日期   	{{book.publish_date}} </li>
	{% endif %}
	<div >
	  <h2 > 借阅信息 </h2>
	  {% if reader  %}
	  <li> 借阅者姓名 {{reader.user}}</li>
	  <li> 借阅日期  {{reader.date_borrow}}</li>
	  <li> 还书日期  {{reader.date_return}}</li>
	  {% else %}
	  <li> 无 </li>
	  {% endif %}
	  <form action="{% url 'booklibrary:bookdetail' book.id stu.id %}" method=post>
		  {% csrf_token %}
	    <div class=actions>
	      <input type=submit value="借阅">
	    </div>
	  </form>

{% endblock %}

library/templates/booklibrary/reader_histroy.html
{% extends "booklibrary/layout.html" %}
{% block title %} 阅读记录 {% endblock %}
{% block link %} 
	<a href=""> 返回 </a>
{% endblock %}
{% block body %}
	<table width="600" border="1" align="center">
	  <tr>
	    <th align="center"> 书名 </th>
	    <th align="center"> 借书日期 </th>	
	    <th align="center"> 还书日期 </th>
	    <th align="center"> 状态 </th>
	  </tr>
	  {% for histroy in histroys %}
	  <tr>
	    <th align="center"> {{histroy.book}} </th>
	    <th align="center"> {{histroy.date_borrow}}</th>
	    <th align="center"> {{histroy.date_return}} </th> 
	    <th align="center"> {{histroy.status}} </th>
	  </tr>
	  {% endfor %}
	</table>	

{% endblock %}

library/templates/booklibrary/reader_info.html
{% extends "booklibrary/layout.html" %}
{% block title %} 个人主页 {% endblock %}

{% block link %}
	<a href=""> 返回  </a>  |
	<a href="{% url 'booklibrary:updatestuinfo' user.id %}"> 修改 </a>
{% endblock %}
{% block body  %}
	<h2> 用户信息 </h2>
	{% if user %}
	<li> 用户名 {{user.username}} </li>
	<li> 学院名 {{user.college}} </li>
	<li> 学号 {{user.sno}} </li>
	<li> 邮箱 {{user.email}} </li>
	{% endif %}

{% endblock %}

library/templates/booklibrary/reader_login.html
{% extends "booklibrary/layout.html" %}
{% block title %} 读者登录 {% endblock %}
{% block linkcss %}
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script>
		 $(function() {

			$("#verify").click(function () {
				this.src = '/verify/'+'?time='+new Date().getTime()
			})

        })

	</script>
{% endblock %}

{% block link %}
	<a href=""> 返回   </a>|
	<a href="{% url 'booklibrary:register' %}"> 注册 </a>
{% endblock %}
{% block body %}
	<h2> 读者登录 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif%}
	<form action="{% url 'booklibrary:loginhandler' %}" method=post id="load">
		{% csrf_token %}
	  <dl>
	    <dt>用户名: </dt>
	    <dd><input type=text name=username size=30 value="{{ request.form.username}}"> </dd>
	    <dt>密码:	 </dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>验证码：<img id="verify" src="{% url 'booklibrary:verify' %}" alt="url不正确"></dt>
	    <dd><input type="text" name="verifycode"></dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="登录">
	  </div>
	</form>
{% endblock %}

library/templates/booklibrary/reader_modify.html
{% extends "booklibrary/layout.html" %}
{% block title %} 个人信息修改 {% endblock %}
{% block link %} 
	<a href=""> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="" method=post>
		{% csrf_token %}
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name=username size=30 value={{user.username}}> </dd>
	    <dt>请输入新密码(不输入就是不修改):</dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name=college size=30 value={{user.college}}> </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name=number size=30 value={{user.sno}}> </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name=email size=30 value={{user.email}}> </dd>
	  </dl>
	  <div class=actions><input type=submit value="确定"></div>
	</form>

{% endblock %}

library/templates/booklibrary/reader_query.html
{% extends "booklibrary/layout.html" %}
{% block title%} 查询  {% endblock %}
{% block link %} 
	<a href=""> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 查询 </h2> 
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
    <div class=actions>
	  <form action="{% url 'booklibrary:checkbook' stu.id %}" method="post">
		  {% csrf_token %}
	    <dd>
	      <select name="item">
		<option value="name"> 书名 </option>
		<option value="author"> 作者 </option>
	      </select>
	      <input type="text" name="query" size="80"> 
	      <input type="submit" value="查询">
	    </dd> 
	  </form>
	</div>
	{% if books %}
	<table width="600" border="1" align="center">
	  <tr>
	    <th align="center"> ISBN </th>
	    <th align="center"> 书名 </th>
	    <th align="center"> 作者</th>
	    <th align="center"> 出版商 </th>
	    <th align="center"> 出版时间 </th>	
	    <th align="center"> 查看信息 </th>
	  </tr>
	  {% for book in books %}
	  <tr>
	    <th align="center"> {{book.id}}</th>
	    <th align="center"> {{book.bookname}} </th>
	    <th align="center"> {{book.author}}</th>
	    <th align="center"> {{book.publish_com}} </th>
	    <th align="center"> {{book.publish_date}}</th>
	    <th align="center"> <a href="{% url 'booklibrary:bookdetail' book.id stu.id %}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	  {% endif %}
	</table>	
{% endblock %}

library/templates/booklibrary/reader_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传图片</title>
</head>
<body>
    <div>
        <h2>上传图片</h2>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            图片名称：<input type="text" name="name">
            <br>
            图片编号：<input type="number" name="index">
            <br>
            图片地址：<input type="file" name="pic">
            <br>
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>

library/templates/booklibrary/register.html
{% extends "booklibrary/layout.html" %}
{% block title %} 注册 {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:index' %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'booklibrary:registerhandler' %}" method=post>
		{% csrf_token %}
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name=username size=30 value="{{ request.form.username}}"> </dd>
	    <dt>密码:</dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>密码<small>(重复)</small>:	</dt>
	    <dd><input type=password name=password2 size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name=college size=30> </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name=number size=30> </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name=email size=30> </dd>
	  </dl>
	  <div class=actions><input type=submit value="注册"></div>
	</form>

{% endblock %}